### PR TITLE
eliminating compiler errors/warnings first batch

### PR DESCRIPTION
**Pull request by diego0815**
please check, I removed the line #define ICACHE_RAM_ATTR IRAM_ATTR and replaced all ICACHE_RAM_ATTR by IRAM_ATTR throughout the project, I hope that's OK

Still some open issues around volatile vs non volatile, especially in SW_Serial (line 147 in Sport_serial.h) and with memcpy

MiLo_RX.ino: In function 'void ISR_TIMER4_COMPA()':
MiLo_RX:924:11: error: invalid conversion from 'volatile void*' to 'void*' [-fpermissive]
  924 |    memcpy(TxData, sportMSPdatastuff, idxs);
      |           ^~~~~~
      |           |
      |           volatile void*

### CODE REVIEW

**Comment by midelic** [comment]
Why did  you changed
ICACHE_RAM_ATTR IRAM_ATTR and replaced all ICACHE_RAM_ATTR by IRAM_ATTR
This line was to keep compatibility with ESP32 in case we have  ESP32
Receiver.
Can you go back on that?

**Comment by diego0815** [comment]
I used Arduino IDE to do the changes instead of a proper editor as usual, I guess that's why for some files no DIFFs are shown but instead the complete file is deleted once and re-added in it's entirety again... very strange.

**Comment by diego0815** [comment]
Well It created a lot of weird warnings, can try to undo let me check

**Comment by diego0815** [comment]
seems like the errors were not directly caused by this define, but it was at around 150 messages, probably all caused by something else, now it still has the same amount of error messages as before the revert

**Comment by diego0815** [comment]
Please check properly what I did with the pointers and the casts of the references... somehow it didn't seem to be happy with the array vs pointer thing one would expect to work out in C. However, it's compiling now, but I'm not so sure about memory leaks and other similar issues

**Comment by diego0815** [comment]
you were right, it worked out without the reference operator, I guess we are ready for primetime :)

**Pull request merged**
