### PR TITLE
change in supported RXs

### PR DESCRIPTION
**Pull request by diego0815**
just in case you are interested, of course nothing tested due to lack of HW

### CODE REVIEW

**Comment by midelic** [comment]
MATEK_RX_R24S has diversity.Ok.

**Comment by diego0815** [comment]
Oh did I mess it up?

The generic diversity/PA json has those 2 pins:
    "ant_ctrl": 9,
    "power_txen": 10,

And in pins.h

  #ifdef MATEK_RX_R24D
    #define SX1280_TXEN_pin            10
    #define SX1280_ANTENNA_SELECT_pin  9
    #define POWER_OUTPUT_FIXED         3
  #elif

Seems identical to me, or do you mean something else?

**Comment by diego0815** [comment]
It seems they dont use the LNA? or how could that be done?

**Comment by midelic** [comment]
How many Matek receivers are? I see 2 in your pull request.
MATEK_RX_R24D and MATEK_RX_R24S.Do the second one has diversity?

**Comment by diego0815** [comment]
S has no diversity but PA

**Comment by diego0815** [comment]
Im wondering if i should download the elrs configurator

**Comment by midelic** [comment]
I merged It is ok.

**Comment by diego0815** [comment]
I was looking so often for this info but it's right in front of us: https://github.com/ExpressLRS/ExpressLRS/blob/master/src/hardware/targets.json
This allocates the generic json file to the various brands RX.

No clue how to use json in the build process but an automatic conversion of the info in those jsons would be cool i think. Better than thousands of defines...

**Pull request merged**
